# ==== parameters ros ==== #
topic_cmd: 'cmd_vel'              # topic to publish the velocity
topic_odom: 'odom'                # topic to get the odometry
topic_scan: 'base_scan_front'     # topic to get the laser scan
robot: 'robot'                    # name of the robot in gazebo

# ==== parameters for the environment ==== #
goal_reached_dist: 0.3            # distance to the goal to consider it reached
collision_dist: 0.2               # distance to the obstacle to consider it a collision
orientation_threshold: 0.1        # threshold to consider the orientation reached
environment_dim: 150              # size of the environment
robot_dim: 4                      # x, y, theta, velocity
action_dim: 2                     # angular and linear
time_delta: 0.1                   # 10 Hz
noise_sigma: 1.0                  # noise for the laser scan

# ==== path to the model and poses ==== #
waypoints: '/ws/src/motion/config/poses.yaml'
path_goal: '/ws/src/motion/config/goals.yaml'
goal_model: '/ws/src/motion/models/target.sdf'
config_path: '/ws/src/motion/config/'

# ==== path weights pre-trained ==== #
model_actor: '/ws/src/motion/src/motion/checkpoints/actor_model.pth'
model_critic: '/ws/src/motion/src/motion/checkpoints/critic_model.pth'

# ==== parameters training ==== #
TYPE: 0                 # (0) -> Train from scratch, (1) -> Load model and continue training, (2) -> Test Model, (3) -> Transfer Learning
BUFFER_SIZE: 1000000    # replay buffer size
BATCH_SIZE: 128         # minibatch size
TAU: 0.001              # for soft update of target parameters
LR_ACTOR: 0.001         # learning rate of the actor 
LR_CRITIC: 0.001        # learning rate of the critic 
WEIGHT_DECAY: 0         # L2 weight decay

LEARN_EVERY: 20         # learning timestep interval
LEARN_NUM: 10           # number of learning passes

EPSILON: 1.0            # explore->exploit noise process added to act step #######
EPSILON_DECAY: 0.000001 # decay rate for noise process 

N_EPISODES: 200000      # maximum number of training episodes
PRINT_EVERY: 10         # print results every n episodes
MAX_T: 150              # maximum number of timesteps per episode
SCORE_SOLVED: 1000000   # minimum score to be considered solved

POLICY_FREQ: 2          # frequency of delayed policy updates
POLICY_NOISE: 0.2       # std of Gaussian noise added to target policy during critic update
CLIP_PARAM: 0.5         # clipping parameter for TD3 policy updates
MAX_ACTION: 1           # maximum action magnitude
DISCOUNT: 0.9999        # discount factor