
# parameters environment specific configuration
target: ~/.models/goal.sdf
topic_cmd: /cmd_vel
topic_odom: /odom
topic_scan: /scan
threshold_arrive: 0.2
num_scan_ranges: 10 
min_range: 0.2

# parameters for the model
BUFFER_SIZE: int(1e6)  # replay buffer size
BATCH_SIZE: 128        # minibatch size
GAMMA: 0.99            # discount factor
TAU: 1e-3              # for soft update of target parameters
LR_ACTOR: 1e-3         # learning rate of the actor 
LR_CRITIC: 1e-3        # learning rate of the critic
WEIGHT_DECAY: 0        # L2 weight decay

LEARN_EVERY: 20        # learning timestep interval
LEARN_NUM: 10          # number of learning passes

N_LEARN_UPDATES: 20    # number of learning updates
N_TIME_STEPS: 10       # every n time step do update

EPSILON: 1.0           # explore->exploit noise process added to act step
EPSILON_DECAY: 1e-6    # decay rate for noise process

N_EPISODES: 2000       # maximum number of training episodes
PRINT_EVERY: 10        # print results every n episodes
MAX_T: 1000            # maximum number of timesteps per episode
SCORE_SOLVED: 1000     # minimum score to be considered solved
