name: dev-env

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Build Docker
        run: make build
    
      - name: Run Simulations
        uses: docker://motion-docker
        run: make setup
      
      - name: Run Tests
        run: make integration
