name: environment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive

  Build:
    needs: [Checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image
        run: docker pull ninim/motion-docker:latest
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

  Running:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Change to root directory
        run: cd "$GITHUB_WORKSPACE"
      - name: Running the tests
        run: make workflow